/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardConfiguration: typeof import('./src/components/BoardConfiguration.vue')['default']
    BoardConfigurationForm: typeof import('./src/components/BoardConfigurationForm.vue')['default']
    BoardExamples: typeof import('./src/components/BoardExamples.vue')['default']
    BoardManager: typeof import('./src/components/BoardManager.vue')['default']
    BoardSelection: typeof import('./src/components/BoardSelection.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LibExamples: typeof import('./src/components/LibExamples.vue')['default']
    LibraryManager: typeof import('./src/components/LibraryManager.vue')['default']
    OtherTools: typeof import('./src/components/OtherTools.vue')['default']
    ProfilesManager: typeof import('./src/components/ProfilesManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SerialMonitorSettings: typeof import('./src/components/SerialMonitorSettings.vue')['default']
    Theme: typeof import('./src/components/Theme.vue')['default']
    Toolbox: typeof import('./src/components/Toolbox.vue')['default']
  }
}
